name: StarBoard
description: Create Star Boards In Your Discord Server.
version: 1.0.0
url: "https://blitz-bots.com"
tags:
  - "fun"
  - "oh yeah"
author: "char"

config:
  reaction: "df"
  reactionCount: 1
  webhookUrl: "dfs"
